version: "3.3"

configs:
  errbot_config:
    file: ./config.py

services:
  errbot:
    image: swarmstack/errbot-docker
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
    ports:
      - "3141:3141"
      - "3142:3142"
    configs:
      - source: errbot_config
        target: /err/config.py
    volumes:
      - ./local_bind_volume_dir:/err/data
